import React from 'react'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import {Footer} from '../components/Footer'
import {Links} from "../components/Links"

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Hello Next.js!</a>
        </h1>
        <h2>
          This is an about page!!
        </h2>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/about.tsx</code>
        </p>

        <Links />
      </main>
      <Footer />
    </div>
    
    
  )
}
